spring:
  redis:
    host: 127.0.0.1
    password:
    database: 0
    timeout: 3000
    jedis:
      pool.max-active: 200
      pool.max-idle: 50
      pool.max-wait: 3000
      pool.min-idle: 10

server:
  port: 8908

request:
  seconds: 5
  max-count: 5